###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    memcached:
        image: 'memcached:alpine'

    redis:
        image: 'redis:alpine'

    mysql:
        image: 'mysql:5.7'
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=php_7
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
        ports:
            - '8991:3306'

    clickhouse:
        image: 'yandex/clickhouse-server:latest'

    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - '.:/app'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8989:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /app
        volumes:
            - '.:/app'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
